# Generated by Django 5.0.2 on 2024-02-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="pay_range",
            field=models.CharField(default="YourDefaultPayRangeValue", max_length=100),
        ),
    ]
