# Generated by Django 5.0.2 on 2024-02-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_post_pay_range"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="pay_range",
            field=models.CharField(default="$0.00", max_length=100),
        ),
    ]
