# Generated by Django 5.0.2 on 2024-02-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_alter_post_pay_range"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="location",
            field=models.CharField(default="City, State", max_length=100),
        ),
    ]
