# Generated by Django 5.0.2 on 2024-02-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_post_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
        migrations.AddField(
            model_name="comment",
            name="experience",
            field=models.CharField(default="null", max_length=60),
        ),
        migrations.AddField(
            model_name="comment",
            name="location",
            field=models.CharField(default="null", max_length=60),
        ),
        migrations.AddField(
            model_name="comment",
            name="name",
            field=models.CharField(default="null", max_length=60),
        ),
    ]
