# Generated by Django 5.0.2 on 2024-02-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_remove_comment_author_comment_experience_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="location",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="name",
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.CharField(default="Candidate", max_length=60),
        ),
    ]
